#!/usr/bin/env bash
high_motifs="AAAABT AGAGAGTA AGCTATAT AGGCAGGC ATGGGAYA ATTGTTAC CAAACTAC CAGYTG CCAATCAG CRACGAS DCGAGACC DGCTTC DHNDATCAGCTGATSD DNKAMCAGSTGKYMNN GAAGGATC GATATRGY GCCVCGCC GCGACCTA GCGCGCGC GGHGGY GTAGATCA GTATCGTA HSDAACAKCTGTCHHW KVGACAGCTGTCRDVV MRWWNCACCTGCTNDNN NBMAACATMTGGTNKM NDNGRCACGTGTCNNND NDRHYACGCRTGKYHND NMDAACAGCTGTYNHN NNAACABCTGTCVNNA NNDACCACGTGGTYND RKRCGCGTGTCCCWN RNGRCGCGTGTCCYND RNMVCASCTGBGBCMT TGACGTCA TGGTGSA TNDRSCACGTGSBANN VRKRMCACCTGCTNVHH
WNAHGGCACGTGYCNDA WNDATCACGTGAYHWDN YBKRVARWAAADWG YGGAR"
low_motifs="AATMAATA ADNRATWAGWANWH AGACGCAG AWBWWTWAAAANWA CGGYTTGA CTGDAR CTKCAA CWHAAAAAAWAAAA GCGCGTCA GTGTGTGY HSDAACAKCTGTCHHW KVGACAGCTGTCRDVV NBMAACATMTGGTNKM NBNAATATAAWVHT NMDAACAGCTGTYNHN NNAACABCTGTCVNNA RNMVCASCTGBGBCMT TACCCCKA TACCTTGA TGACGTCA WAYYAWATWTRKVV WHWAATAAAACNVW YBKRVARWAAADWG"

motifs_high2="ACGCRTG ATCAGCTG RGTA"
motifs_low2="ACATMTGG CTGDAR TACTGTAG"
motifs_select1="GAGG BGAGG AGAA ASAAD"
motifs_select2="GATC"
motifs_select3="ANNNATCAGCTG CNNNATCAGCTG GNNNATCAGCTG TNNNATCAGCTG ATCAGCTGATCAGCTG"
motifs_select4="ANNGATC CNNGATC GNNGATC TNNGATC GATCGATC"
# REBASE E. coli REL606
motifs_select5="ATGCAT TGANNNNNNNNTGCT"
# From Blow et al. (2016) https://doi.org/10.1371/journal.pgen.1005854
motifs_select6="ATTAAT AATT CATG RAATTY ATCGAT CTCGAG TTAA ATGCAT GANTC AGCT CTAG"
# known RM system motifs for E. coli K-12
motifs_select7="AACNNNNNNGTGC"

motifs2="$motifs_high2 $motifs_low2 $motifs_select1 $motifs_select2 $motifs_select3 $motifs_select4 $motifs_select5 $motifs_select6 $motifs_select7"

prepare_dir () {
    dir="$1"
    motif="$2"
    if [[ -e $dir/PATTERN ]]; then
        echo "Skipping making $dir/PATTERN"
    else
        mkdir -p $dir
        echo $motif > $dir/PATTERN
        ln -sf ../motif.makefile $dir/Makefile
    fi
}

motifs="$high_motifs $low_motifs $motifs2"
for motif in $motifs
do
    prepare_dir $motif $motif
done

# GGN_4
prepare_dir GGN_4 GGNGGNGGNGGN
prepare_dir GGN_10 GGNGGNGGNGGNGGNGGNGGNGGNGGNGGN
prepare_dir AGGCTT_4 AGGCTTAGGCTTAGGCTTAGGCTT
prepare_dir AGGY_7 AGGYAGGYAGGYAGGYAGGYAGGYAGGY
